#!/usr/bin/env python3
"""Build the world map + country centroids from world-atlas TopoJSON.

Outputs:
    web/js/geo-data.js     simplified land rings + interior borders (ES module)
    data/centroids.json    country name -> [lat, lon] (largest-polygon centroid),
                           used by ingest to place locations that match no base

Usage:
    curl -sO https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json
    curl -sO https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json
    python3 tools/build_geo.py land-50m.json countries-50m.json

Source data: Natural Earth (public domain) via world-atlas (ISC).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOL_LAND = 0.09     # Douglas-Peucker tolerance, degrees
TOL_BORDER = 0.15
MIN_LAT = -60       # drop Antarctica


def decode_arcs(topo):
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    out = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        out.append(pts)
    return out


def ring_from(arcs, idxs):
    pts = []
    for i in idxs:
        seg = arcs[i] if i >= 0 else arcs[~i][::-1]
        pts.extend(seg if not pts else seg[1:])
    return pts


def dp(pts, tol):
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]
        bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        norm = (dx * dx + dy * dy) ** 0.5 or 1e-12
        best, bi = -1.0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            d = abs(dy * px - dx * py + bx * ay - by * ax) / norm
            if d > best:
                best, bi = d, i
        if best > tol:
            keep[bi] = True
            stack += [(a, bi), (bi, b)]
    return [p for p, k in zip(pts, keep) if k]


def dp_ring(ring, tol):
    """Closed rings start and end on the same point, which degenerates DP; split them first."""
    if len(ring) < 8:
        return ring
    mid = len(ring) // 2
    return dp(ring[: mid + 1], tol) + dp(ring[mid:], tol)[1:]


def flat(ring):
    out = []
    for x, y in ring:
        out += [round(x, 2), round(y, 2)]
    return out


def area_centroid(ring):
    a = cx = cy = 0.0
    for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]):
        c = x0 * y1 - x1 * y0
        a += c
        cx += (x0 + x1) * c
        cy += (y0 + y1) * c
    if abs(a) < 1e-9:
        xs, ys = zip(*ring)
        return abs(a), sum(xs) / len(xs), sum(ys) / len(ys)
    return abs(a) / 2, cx / (3 * a), cy / (3 * a)


def main():
    land = json.load(open(sys.argv[1]))
    countries = json.load(open(sys.argv[2]))

    arcs = decode_arcs(land)
    rings = []
    for geom in land["objects"]["land"]["geometries"]:
        polys = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
        for poly in polys:
            ring = ring_from(arcs, poly[0])
            if max(p[1] for p in ring) < MIN_LAT:
                continue
            simple = dp_ring(ring, TOL_LAND)
            if len(simple) < 4:
                simple = ring[:: max(1, len(ring) // 4)][:4]
                if len(simple) < 3:
                    continue
            rings.append(flat(simple))

    carcs = decode_arcs(countries)
    use = {}
    centroids = {}
    for geom in countries["objects"]["countries"]["geometries"]:
        polys = geom.get("arcs") or []
        polys = polys if geom["type"] == "MultiPolygon" else [polys]
        best = None
        for poly in polys:
            for ring in poly:
                for i in ring:
                    k = i if i >= 0 else ~i
                    use[k] = use.get(k, 0) + 1
            outer = ring_from(carcs, poly[0])
            a, cx, cy = area_centroid(outer)
            if best is None or a > best[0]:
                best = (a, cx, cy)
        name = (geom.get("properties") or {}).get("name")
        if name and best:
            centroids[name] = [round(best[2], 2), round(best[1], 2)]

    borders = []
    for k, n in use.items():
        if n < 2:
            continue
        line = carcs[k]
        if max(p[1] for p in line) < MIN_LAT:
            continue
        simple = dp(line, TOL_BORDER)
        if len(simple) >= 2:
            borders.append(flat(simple))

    out = ROOT / "web" / "js" / "geo-data.js"
    with out.open("w") as f:
        f.write("/* Generated by tools/build_geo.py from Natural Earth 1:50m via world-atlas.\n"
                "   Flat [lon,lat,lon,lat…] rings. */\n")
        f.write("export const LAND = " + json.dumps(rings, separators=(",", ":")) + ";\n")
        f.write("export const BORDERS = " + json.dumps(borders, separators=(",", ":")) + ";\n")
    (ROOT / "data" / "centroids.json").write_text(json.dumps(dict(sorted(centroids.items())), indent=0))
    print(f"land rings {len(rings)}, borders {len(borders)}, centroids {len(centroids)} -> {out}")


if __name__ == "__main__":
    main()
